
namespace BlackberryPlatformServices.Screen.Types
{
    public enum DisplayMetricCountType: int
    {
        SCREEN_DISPLAY_METRIC_ATTACH_COUNT = 0,
        SCREEN_DISPLAY_METRIC_POWER_ON_COUNT = 1,
        SCREEN_DISPLAY_METRIC_IDLE_COUNT = 2,
        SCREEN_DISPLAY_METRIC_EVENT_COUNT = 3,
        SCREEN_DISPLAY_METRIC_UPDATE_COUNT = 4,
        SCREEN_DISPLAY_METRIC_UPDATE_PIXELS = 5,
        SCREEN_DISPLAY_METRIC_UPDATE_READS = 6,
        SCREEN_DISPLAY_METRIC_UPDATE_WRITES = 7,
    }
}
